// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type Post struct {
	ID        int32
	Title     string
	Content   string
	Image     sql.NullString
	UserID    int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID        int32
	Name      string
	Email     string
	CreatedAt time.Time
	UpdatedAt time.Time
}
