DELETE http://localhost:8080/users/6
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3Rhc2RAZXhhbXBsZS5jb20iLCJleHAiOjE3NTQxMjUzOTcsInVzZXJfaWQiOjZ9.4mJorrYrRNFENFtakUCW-NTfza-ZLM7MAmFZsYDaHn4